//
// Created by 王勇椿 on 2020/9/24.
//

#ifndef UNIX_ADVANCED_PROGRAMING_PARENT_CHILD_PROCESS_SYNC_H
#define UNIX_ADVANCED_PROGRAMING_PARENT_CHILD_PROCESS_SYNC_H

void TELL_WAIT_V2(void);
void TELL_PARENT_V2(void);
void WAIT_PARENT_V2(void);
void TELL_CHILD_V2(void);
void WAIT_CHILD_V2(void);
#endif //UNIX_ADVANCED_PROGRAMING_PARENT_CHILD_PROCESS_SYNC_H
